version = 0.1
[default.deploy.parameters]
stack_name = "websocket-demo"
resolve_s3 = true
s3_prefix = "websocket-demo"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
disable_rollback = true
